### ISSUE TITLE
Issue with Atkinson, Kirby & Smith (2015)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#107]
Document Key:atkinson2015speaker
Contributors: @peeter-t2 

Is the experiment in this document the same as in another document in CHIELD?
[Atkinson, Smith & Kirby (2016) (EvoLang)](https://chield.excd.org/document.html?key=evolang11_48)

**Comment by peeter-t2** [comment]
Good question, the experiment is different, but hypotheses are related. 2015 made stimuli have variation in phonology, 2016 had speakers generate this variation through mistakes. The underlying hypothesis, about number of speaker models was related, but 2015 did this for phonology, while 2016 more with morphology. Though both definitely include the consideration of number of speaker models. Not sure if this is distant enough.

How do you generally want to handle when one author makes several studies on one hypothesis keep only one entry, or several? Do you want to keep it minimal for each hypothesis, or include the updateds on confirmed/not or some details in connections?

Are you aiming for one entry per hypothesis or per experiment?

**Comment by seannyD** [comment]
The aim is to code by document.  So if someone makes the same hypothesis in different papers, but with different experiments/methods, then they get entered multiple times.  This makes it easy to see robust support for a hypothesis. 
So in this case, keeping both documents is fine.
