### ISSUE TITLE
Question about Dunbar (2004)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#133]
Document: [dunbar2004gossip](https://chield.excd.org/document.html?key=dunbar2004gossip)
Contributors: @seannyD 

Should include correlation between pop size and brain size, but perhaps that's originally from another publication?

**Comment by SimonGreenhill** [comment]
...that would be Dunbar '92 https://www.sciencedirect.com/science/article/pii/004724849290081J

**Comment by SimonGreenhill** [comment]
added in #134

**Comment by seannyD** [comment]
Woah, the system works!
