### ISSUE TITLE
Question about Little, Eryilmaz & de Boer (2017)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#147]
Document: [little2017conventionalisation](https://chield.excd.org/document.html?key=little2017conventionalisation)
Contributors: @hanachronism 

modality > iconicity  (confirmed: no)

The standard interpretation here is that the authors hypothesised a link between modality and iconcity, but this was not supported.  (as opposed to the authors hypothesising that there would be no effect of modality).  Is that right?  Adding a quote to the notes would help clarify.

**Comment by hanachronism** [comment]
Yes, the authors hypothesised a link between modality and iconcity, but this was not supported, that's what I was trying to communicate. I'll add a quote.
