### ISSUE TITLE
Question about Kusters (2008)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#151]
Document: [kusters2008](https://chield.excd.org/document.html?key=kusters2008)
Contributors: @peeter-t2 

Is there a particular reason for naming the variable "morphological complexity: inflection" as opposed to just "morphological complexity"?  Sorry, trying to maximise the overlap between hypotheses, and my knowledge of morphology is not good enough to know if this is an important distinction!

**Comment by peeter-t2** [comment]
This can easily be simply "morphological complexity", I was here aiming to follow the "superordinate: subordinate" setup.

The author is throughout explicit in talking about complexity in inflectional morphology only, but he does not tackle relationship with morphology generally, and it seems quite reasonable to simply call this morphological complexity. 

If there were some day a way to process the colons in the variables automatically, this "inflectional" could be useful extra information, but for now, simple "morphological complexity" seems sensible.

**Comment by seannyD** [comment]
OK, that seems like justification for keeping it.  The Explore page recognises superordinate:subordinate relations can can cluster them with the "cluster" button.  I'll have to think about how this can be extended to other search functions.

**Comment by seannyD** [comment]
e.g. we could have a "include subordinate variables" option for the "find paths" function.
