### ISSUE TITLE
Question about Smith & Wonnacott (2010)

### ISSUE THREAD

**Issue by AleksandrsBerdicevskis** [CHIELDOnline/CHIELD#157]
Wouldn't "*iterated* learning and use" suit better than "repeated"? To me, "repeated" means "repeated exposure (for a single individual)", while the authors mean transmission over generations.

Document: [smith2010eliminating](https://chield.excd.org/document.html?key=smith2010eliminating)
Contributors: @peeter-t2

**Comment by seannyD** [comment]
Good point.  I also edited it so that the variables are split up.
[https://github.com/CHIELDOnline/CHIELD/pull/160](https://github.com/CHIELDOnline/CHIELD/pull/160)

**Comment by AleksandrsBerdicevskis** [comment]
The split looks good, but I now when I've looked at the graph again I am not sure about _plural marker_ as an indicator of _regularity in language_. It's the distribution of several competing markers that is an indicator, not the presence of the marker.

Do we need _regularity in language_ instead of _regularity_?

(Sorry if I should have started a separate thread for every comment.)

**Comment by seannyD** [comment]
Hmm.  Good point.  The way the operationalise regularity in the experiment is by measuring the extent of plural marking (vs morphological marking) in the language. This link is supposed to represent that.  So it could be "plural marking" or "lexical marking of plural" or "marking strategy: lexical" or even "lexical marking to morphological marking ratio"?  Hmm. Ideas welcome.

Re: "regularity in language": "regularity" is quite vague.  There could be other variables that represent the regularity of something else (e.g. regularity of rhythm).  But "regularity of language" is not very specific either.  But let me know if you have a better idea for a label.

**Comment by AleksandrsBerdicevskis** [comment]
No, they have two competing markers (both lexical) and measure the properties of the distribution of these markers (proportion of the chain-initial majority marker and, most importantly, predictability of markers [from the noun stem]). I'd suggest "distribution of plural markers" if we want to be more general, "predictability of plural marking [markers?]" if we want to be more specific.

Regularity: no strong opinion. I think it can be left as it is for now and resort to semicolons later if need be.
