### ISSUE TITLE
Question about Pagel, Atkinson & Meade (2007)

### ISSUE THREAD

**Issue by AleksandrsBerdicevskis** [CHIELDOnline/CHIELD#159]
Is it legitimate to claim that the relation is "causal" here and not "correlational"? I opted for the more conservative "correlational" when adding e.g. Hamilton et al. 2016. 

The guidelines state that "statistical analysis of data (e.g. cross-cultural typology, corpus, survey)" will "most often" yield correlational relation, "but could be causal depending on the methods." What are the criteria for the relation to be causal in, for instance, corpus studies?

Document: [Pageletal2007](https://chield.excd.org/document.html?key=Pageletal2007)
Contributors: @SimonGreenhill

**Comment by seannyD** [comment]
Good question, this is not currently clear.  The causal graphs should represent the high-level *hypothesis*, not necessarily the conclusions that can be drawn from the paper.  Causality is very difficult to *prove*.

Most hypotheses will state causal claims, and a causal link can have support from a statistical analysis.  But the correlation relation is useful to show tests that were actually carried out.  For example, Lupyan & Dale don't actually hypothesise a direct causal link from population size to morphological complexity, but they do explicitly hypothesise that they should be correlated, and the main analysis in the paper shows a correlation between the two.

I think that the guidelines are trying to point out that some advanced statistical methods have causal interpretations, while others have only correlational interpretations.  I'll try to make this clearer, probably starting a FAQ would be a good idea.

**Comment by seannyD** [comment]
Yes, keep the causal relation.  Thanks!

(I shouldn't have said "advanced" methods, I just mean things like causal inference and mediation analysis which have assumptions that have causal interpretations, as opposed to a standard linear regression which does not)
