### ISSUE TITLE
Question about Szmrecsanyi & Kortmann (2009)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#195]
Document: [szmrecsanyi2009between](https://chield.excd.org/document.html?key=szmrecsanyi2009between)

Change "language contact vs language isolation" to just "language contact"?

**Comment by AleksandrsBerdicevskis** [comment]
Yes. 
The only reason why I chose "contact vs. isolation" was to avoid adding new variables, since this one already existed. I actually think it's best to replace it by "language contact" in other graphs, too.
We can't edit variables directly, can we? (But I assume you can.)
