### ISSUE TITLE
Unification of variable labels

### ISSUE THREAD

**Issue by AleksandrsBerdicevskis** [CHIELDOnline/CHIELD#199]
Do we have an explicit or implicit strategy of how that could be done systematically? There are currently quite a few cases when similar things have different names.
One (rather cheap) way would be to use the colon as much as possible. 

To give a simple example: for "contact", we currently have:
_language contact vs. isolation
long-term bilingual contacts
population contact
short-term adult language contacts_

I'd change these into something like:
_contact: population
contact: language
contact: language: long-term, bilingual
contact: language: short-term, adult_

Similar thing could be done for "complexity", though that would be much more complex.

Obviously, this does not solve all the problems, and actually creates some new, since we have to make some non-trivial ontological decisions.

**Comment by HedvigS** [comment]
I'd be happy to spend some time help trimming the labels and make suggestions for merges or further specification. 

@seannyD what's your feelings?

Should we just clone the repos, make some edits of this kind and then send a pull request and you can review it then?

If need be, one could even use the github wiki for adding more info on a certain variable. Hopefully the variable labels are enough informative that that isn't so necessary.

**Comment by seannyD** [comment]
Yes, the idea is that occasionally we edit labels like this to unify things (I haven't been very on top of this!). The suggestions above sound good to me, and feel free to suggest other changes (prob in separate issue so we can close them). 

My thought was that when we agreed, I'd make a global change with a little script. You could do it yourself by forking, editing and making a pull request (and adding some context in the commit message). But no pressure. At the moment, there's no way of easily attributing large-scale label editing to you (as opposed to adding and editing individual documents).

**Comment by HedvigS** [comment]
Discussing specific merges in issues and then doing an overall edit sounds good to me!
