### ISSUE TITLE
"Update variable change for all rows?" confusing

### ISSUE THREAD

**Issue by catherinesheard** [CHIELDOnline/CHIELD#214]
This might just have been me, but I found the meaning of the question "Update variable change for all rows? Yes/Cancel" very confusing, and I've ended up epically messing up the entry that I'm currently working on because I blindly clicked "yes". I'm also about 80% sure that I screwed up one of my earlier entries because I didn't get what this question was asking me. (I will double-check this at some point.)

The options of "Yes/No" or "Yes/No/Cancel" (since the "Cancel" button isn't actually a cancel button, but a "carry on" button) would help? Or rephrasing it as "Update variable name change on all other rows?" ?

Or, I dunno, learning point for Catherine, don't click on things unless you actually know what they do.

**Comment by seannyD** [comment]
Yes / No / Cancel would be ideal, but hard to implement right now.
I've changed the text to:

>   You changed a variable name from X to Y. Click 'Yes' to apply this change to all rows, or 'Cancel' to apply this change just for this link.
