### ISSUE TITLE
Documents list latex symbols in title not rendering

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#233]
e.g. "Absolute Komplexit\"at in der Nominalflexion: Althochdeutsch, Mittelhochdeutsch, Alemannisch und deutsche Standardsprache"
"Studying language change using price equation and P\'olya-urn dynamics" - fix latex symbol"

**Comment by SimonGreenhill** [comment]
There's a PR that fixes this in https://github.com/CHIELDOnline/CHIELD/pull/261 

I'm not sure why the acutes and diareses are not being caught by the regexes [here](https://github.com/CHIELDOnline/CHIELD/blob/master/processing/detexify.R#L4). I suspect it's an escaping issue (either the reading in of the `\"` is leading to breeding slashes `\\"` or this is happening elsewhere). 

However, I didn't know if anything else was relying on the current approach for handling acutes/diareses, so I thought it safer to just add some new matches.

Also, I decided to spell out the 5 permutations of both acutes and diareses as this should be (marginally) quicker than invoking the regex engine.

**Comment by seannyD** [comment]
This is great! I'm very surprised that there's no out-of-the-box way to do this. Testing now...
