### ISSUE TITLE
Collaborators page

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#289]
Generate list of people who should collaborate based on number of nodes in common, but who have not published together.
Requires some processing in deploy.sh to split authors from bibtex, and prob some cleaning of bibtex names.

**Comment by seannyD** [comment]
Started work:  Cleaned author list, compiled new table of authors in the db, wrote SQL command, started on authors.html.

**Comment by seannyD** [comment]
Need to add a page "Who should I collaborate with?"

`getConnectionsBetweenAuthors.php` already filters author connections from the same publications, a version of this just needs to be made which is searchable.

Note that we could also just create an "author list" page, with links to an "author details" page. The details page would list their publications, variables studied, co-authors, and suggested co-authors. This is less gimmicky, though.

**Comment by SimonGreenhill** [comment]
The 'author list' page would also be really interesting and useful as a way to check an authors ~fetishes~ research interests, and track down other work.
