### ISSUE TITLE
Question about Evans (2003)

### ISSUE THREAD

**Issue by ruthsinger** [CHIELDOnline/CHIELD#322]
Document: [evans2003context](https://chield.excd.org/document.html?key=evans2003context)
Contributors: @angarikadeb 
Is this bit: "linguistic practices > linguistic ideologies" meant to say that Evans (2003) hypothesises that certain language practices cause certain language ideologies? I'm not sure if Evans (2003) makes this claim. This is a bit controversial, for two reasons. Firstly the causal link between language practices and language ideologies would usually be understood to go the other way (language ideologies > language practices), although some now argue it's both ways <=>. Also, from the link is usually understood as somewhat indirect, because people often don't practice what they preach. Also the phrase 'language ideologies' is conventionally used, not 'linguistic ideologies', so it might be a better name for the variable. Similarly for language(*linguistic)practices.

**Comment by ruthsinger** [comment]
Hi Sean, I'm glad that those comments were useful. I would be happy to edit the entry for Evans (2003) and contribute some more papers, maybe even 5! I'm reading papers on language evolution at the moment as I'm working on a fellowship proposal on multilingualism and linguistic diversity that includes a language evolution component. I've started reading your PhD thesis, which Matt Spike suggested, it's very interesting! Any other recommendations for readings in this area, that are relatively accessible to the outsider would be great, Ruth

**Comment by angarikadeb** [comment]
Hi Ruth
Thanks for your comments, I understand your point. It stand to logic that ideologies would precede the existence of certain practices.
When I coded this paper, I didn't exactly mean language ideologies, but something more like linguistic categories and ideas (which were referred to as ideologies at one point in the paper) that arise from 'cultural practices'.
I do agree that using a better word would make the meaning clearer - so please feel free to edit. 
Else, I can do the same - possibly after a discussion with you.
And like Sean said, I am not an expert in the area myself so your comments will help clarify my concepts in the field.

**Comment by ruthsinger** [comment]
Hi,
I had a look at the paper and Nick did use the phrase 'linguistic ideologies' twice. These are probably mistakes as the rest of the paper he uses 'language ideologies'. The phrase 'linguistic ideologies' and I used to use it myself but because 'language ideologies' is a conventionalised expression I think it will make a better variable, as it is what people will search for, Ruth

**Comment by seannyD** [comment]
Thanks a lot for this! The page is updated: [https://chield.excd.org/document.html?key=evans2003context](https://chield.excd.org/document.html?key=evans2003context).

When people click the "Discussion history" button, they'll find this discussion.
