### ISSUE TITLE
Question about Wray & Grace (2007)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#336]
Document: [wraygrace2007](https://chield.excd.org/document.html?key=wraygrace2007)
Contributors: @HedvigS 

This is an important paper to include.  I was wondering if there was a way to connect it to the statistical work on morphological complexity (e.g. Lupyan & Dale).  Currently there's only "linguistic complexity", do Wray & Grace get any more specific? Also to Hannah Little's [experiment on foreigner directed speech](https://chield.excd.org/document.html?key=little2011role)?  e.g. Little's node could be changed from "foreigner directed speech" to "communication with non-native speakers".

**Comment by HedvigS** [comment]
Lupyan & Dale (2015) was going to be my 3rd submission ^^!

Wray & Grace mainly discuss compositionality, regularity, lack of norms and what I called "Informational autonomy of utterances" (i.e. how much information is implicit/shard knowledge) They briefly discuss expressivity as well actually, controversially!

I'll do a re-read again to see how to better tease it apart.
