### ISSUE TITLE
Question about Wichmann & Holman (2009)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#350]
Document: [wichmann_holman_2009](https://chield.excd.org/document.html?key=wichmann_holman_2009)
Contributors: @HedvigS 

Good to see this in the database!  However, "faster rates of change" should not have a qualifier (i.e. remove "faster"), and be specific about what's changing.  There's an existing variable "lexicon:rate of change" which might suit this.

**Comment by HedvigS** [comment]
Ah, good point. I picked faster rates of change because someone else had entered it for Nettle, but you're right that your option is better.

**Comment by HedvigS** [comment]
When trying to edit the data through the web interface I still get "There may be an error with the submission, please check data and try again." (both on Chrome and Safari) and I don't have authority to push changes to the Github repos directly.

Can I get given some push rights as HedvigS to this repos?

**Comment by seannyD** [comment]
Both problems are strange, so I'd like to sort this out, if you don't mind helping me.

Web interface: What are the exact steps that are you taking? Others have managed to successfully edit their documents in the last day.

Pushing to github: Anyone should be able to make a pull request to this repository. Are you forking this repository and making a pull request? Or cloning it directly?

**Comment by HedvigS** [comment]
Thanks, yes I'd also like to figure it out. I feel a bit stupid.

Web interface: I tag in as my username on github, navigate to the relevant document, click "edit data" and edit the relevant rows. I get the message about doing a global change ("Click 'Yes' to apply this change to all rows"). Go to the tab "submit" and click submit, and that's where I get "There may be an error with the submission, please check data and try again."

Pushing to github: I made a local clone and made changes in the master branch and tried to push. That's normally what I do for the other reposes I'm. I also tried to create my own branch and publish it and create a pull request. Got same the exact same error message both when trying to push to master and push my own branch.

It's probably me fault. I'll go see if Robert is in the office across the hall.

**Comment by seannyD** [comment]
Web interface: Hmm, I tried those steps and successfully created a pull request:
https://github.com/CHIELDOnline/CHIELD/pull/354

Pushing to github: You need to make a fork on the github website, then clone that repository, push changes to it, then make a pull request on github.

**Comment by HedvigS** [comment]
Web interface: yeah I don't know what's up there

pushing to github: okay, I thought branching and pushing would do it but it doesn't, I'll try what you said.

**Comment by SimonGreenhill** [comment]
This is fixed and should be closed.
