### ISSUE TITLE
Question about Stanford & Pan (2013)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#374]
Document: [stanford_pan_2013](https://chield.excd.org/document.html?key=stanford_pan_2013)
Contributors: @HedvigS 

This is an important paper to include. Is there any indication about what *kind* of change Stanford & Pan are talking about? (lexicon, morphology, maybe both?). Also, "faster" should be dropped from the label.

**Comment by SimonGreenhill** [comment]
looks like phonology: 

>>> sociophonetic analyses of in‐married women and local villagers show that the in‐married women acquired the local variety in most respects but not in aspirated consonants. To the limits of their phonological ability as adult learners, the wives followed the local sociolinguistic norm: they acquired the husbands’ variety. By contrast, in societies experiencing greater external cross‐cultural contact, exogamous women sometimes use their liminal status to challenge such gendered sociolinguistic expectations.

**Comment by HedvigS** [comment]
Yeah, it's phonology. Sorry!

**Comment by seannyD** [comment]
Updated in #534

**Comment by HedvigS** [comment]
I think I should get into this again and do changes in the proper way with pull requests etc, I'm sorry I haven't done so.
