### ISSUE TITLE
Export network as a DOT file

### ISSUE THREAD

**Issue by CHIELDOnline** [CHIELDOnline/CHIELD#42]
# Task: Create a function that converts a vis.js network into a DOT file

At the moment, the file `app/Site/js/visualisation/exportNetwork.js` includes code to export to PNG.  That's easily done directly from the canvas.

It would also be good to be able to export to an editable format.  For example, the [DOT format for network specification](https://en.wikipedia.org/wiki/DOT_(graph_description_language)).  The user could then use Gephi to export.

See [this issue in vis.js](https://github.com/almende/vis/issues/1784)
And a preliminary attempt (for another visualisation package) [here](https://github.com/datastorm-open/visNetwork/issues/204#issuecomment-372068374).

The other option is to create an SVG file, compatible with Inkscape.

**Comment by seannyD** [comment]
Now implemented for Explore:
[app/Site/js/visualisation/exportToDot.js](https://github.com/CHIELDOnline/CHIELD/blob/master/app/Site/js/visualisation/exportToDot.js)

Seems to work with GraphViz.
